/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Camera: typeof import('./src/components/camera/index.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/index.vue')['default']
    TBadge: typeof import('tdesign-mobile-vue')['Badge']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TSwitch: typeof import('tdesign-mobile-vue')['Switch']
  }
}
